### ISSUE TITLE
SIKE: question

### ISSUE THREAD

**Issue by henrydcase** [Microsoft/PQCrypto-SIDH#12]
The specification for SIKE (http://www.sike.org/files/SIDH-spec.pdf) says that values for cSHAKE256 customization bit strings are F=2, G=0 and H=1.

In this implementation, those values (called P,G,H) are encoded on 16 bits, which means that value of let say H customization byte-string will be {0x01, 0x00}.
See here: https://github.com/Microsoft/PQCrypto-SIDH/blob/e5b378378d0f316ed0f602189dfd7f16d3021148/src/sha3/fips202.c#L442

Any idea why it was done that way?

The problem with this is that value of cSHAKE digest depends on length of the byte string, so it maybe would be good to improve spec or change code (and then KATs)

**Comment by patricklonga** [comment]
This is going to be changed soon.
