### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Microsoft/PQCrypto-SIDH#15]
I would like to point out that identifiers like “[`__P503_INTERNAL_H__`](https://github.com/Microsoft/PQCrypto-SIDH/blob/06b6cddd438c96b85a08b6a49338d0e615d8d971/src/P503/P503_internal.h#L7 "Update candidate")” and “[`__P751_API_H__`](https://github.com/Microsoft/PQCrypto-SIDH/blob/06b6cddd438c96b85a08b6a49338d0e615d8d971/src/P751/P751_api.h#L7 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by patricklonga** [comment]
Not at this point. But I'll have it in mind for a future update. Thanks for the recommendation.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
