### ISSUE TITLE
Surgestion: Name change

### ISSUE THREAD

**Issue by slickpockets** [Microsoft/PQCrypto-SIDH#21]
Please Consider name change to Eliptic Curve Cartography, if the name wasnt allready passed over in favour of SIDH.... 1 biased opinion of course but there is no way one can get "tits or dicks" explaining that they are super into Supersingular Isogeny Diffie-Hellman key exchange/cryptography. i am aware this would effect many pre-existing git/subversoin/mercurial etc but this is the price of having a bad ass name 
and will likely be the deciding factor for its eventual adoption.

**Comment by patricklonga** [comment]
Thanks but no thanks.
