### ISSUE TITLE
Which bits to ignore when the secret agreement is finished

### ISSUE THREAD

**Issue by MRandl** [microsoft/PQCrypto-SIDH#24]
Hello !
Computer science student here, I was fidgeting around with the library, and i saw that on the secret agreement method using p751, there is the following comment : `Output: a shared secret SharedSecretB that consists of one element in GF(p751^2) encoded in 188 bytes.` 

Now, 751 * 2 = 1502, and 188 * 8 = 1504. That would mean that two bits are redundant, right ?

However, when running the following mock program :
``` c 
#include <stdio.h>
#include "P751_api.h"

#define BTBP "%c%c%c%c%c%c%c%c"
#define BTB(byte)  \
  (byte & 0x80 ? '1' : '0'), \
  (byte & 0x40 ? '1' : '0'), \
  (byte & 0x20 ? '1' : '0'), \
  (byte & 0x10 ? '1' : '0'), \
  (byte & 0x08 ? '1' : '0'), \
  (byte & 0x04 ? '1' : '0'), \
  (byte & 0x02 ? '1' : '0'), \
  (byte & 0x01 ? '1' : '0') 

int main() {

	unsigned char APri[47];
	unsigned char APub[564];
	random_mod_order_A_SIDHp751(APri);
	EphemeralKeyGeneration_A_SIDHp751(APri, APub);
	
	unsigned char BPri[48];
	unsigned char BPub[564];
	random_mod_order_B_SIDHp751(BPri);
	EphemeralKeyGeneration_B_SIDHp751(BPri, BPub);

	unsigned char secretAgreementA[188];
	unsigned char secretAgreementB[188];

	EphemeralSecretAgreement_A_SIDHp751(APri, BPub, secretAgreementA);
	EphemeralSecretAgreement_B_SIDHp751(BPri, APub, secretAgreementB);

	printf(BTBP"\n", BTB(secretAgreementA[0]));
	printf(BTBP"\n", BTB(secretAgreementA[187]));

	return 0;
}
```

we see no particular pattern in either the first or last byte. My question is, where are the two missing bits ? 

Thanks in advance,
MRandl

**Comment by patricklonga** [comment]
Elements (a+b*i) over GF(p751^2), where "a" and "b" are defined over GF(p751), are encoded as {a, b}, with "a" in the lowest memory portion. In turn each of these elements over GF(p751) are encoded as 94 octets in little endian format (i.e., the least significant octet is located in the lowest memory address). 
This means that the top bits of elements "a" and "b" are clear (in your example top bits of the bytes secretAgreementA[93] and secretAgreementA[187] should be zero).

**Comment by MRandl** [comment]
Thanks a lot! Sorry to have bothered!
