### ISSUE TITLE
Undefined left shift by -1 in ord2w_dloghyb

### ISSUE THREAD

**Issue by jschanck** [microsoft/PQCrypto-SIDH#39]
It is possible for the following line to be executed with ord=1, in which case the left shift is undefined.
https://github.com/microsoft/PQCrypto-SIDH/blob/0b6f740ceae03b54282bc2ae940a3f32f3abaa98/src/compression/dlog.c#L183
It would be OK to multiply through by 2 or 4 here, there's no risk of overflow.

**Comment by patricklonga** [comment]
Thanks for reporting this issue, John. A related variable wasn't properly corrected to the range [0, p-1] before being tested against 0. I pushed a fix.
