### ISSUE TITLE
when is scheme not secure

### ISSUE THREAD

**Issue by glycerine** [Microsoft/PQCrypto-SIDH#4]
Given this cryptic note at the top of the repo

> SECURITY NOTE: the scheme is NOT secure when using static keys.

Could you elaborate on what "static" means? Are static keys ever the default?

**Comment by christianpaquin** [comment]
Static keys in the sense of "re-used" keys. This version of SIDH is only secure in ephemeral settings: new keys must be generated for every session. As an example, this is what we do in our [OpenSSL integration](https://github.com/open-quantum-safe/openssl). The warning is for developers wishing to integrate SIDH in other protocols/products.

**Comment by glycerine** [comment]
@christianpaquin: got it. thank you.

**Comment by ramsestom** [comment]
Can't find this note. Is this still the case with version 3 or can static keys be used with SIDH v3.0 without any security concern?

**Comment by patricklonga** [comment]
Version 3 of the library includes two protocols: SIKE (a key encapsulation scheme) and SIDH (the original supersingular isogeny Diffie-Hellman key exchange). SIKE is IND-CCA2 secure, which means that it's ok to reuse the key pair generated by crypto_kem_keypair_SIKEpXXX(), whereas SIDH is insecure with *re-used* keys, as before. The note you are looking for can be found in P503_api.h and P751_api.h.
