### ISSUE TITLE
Porting to javascript version

### ISSUE THREAD

**Issue by procoru** [Microsoft/PQCrypto-SIDH#5]
I slightly changed SIDH.h and makefile to build the web version using emscripten.
My changes here:
https://github.com/procoru/PQCrypto-SIDH/commit/539c0f2d5e14682d3cf1a893e4753423e0ce592a

Demo here: http://sidh.getforge.io/

**Comment by tomekmarchi** [comment]
Would like to express my extreme interest in this. Would a Node module be a possibility?

**Comment by patricklonga** [comment]
The link doesn't seem to work anymore.
