### ISSUE TITLE
Imprecise specification of `get_2_isog` and `get_4_isog`

### ISSUE THREAD

**Issue by bshvass** [microsoft/PQCrypto-SIDH#52]
In `src/ec_isogeny.c` the specification of `get_2_isog` states that
```
void get_2_isog(const point_proj_t P, f2elm_t A, f2elm_t C)
{ // Computes the corresponding 2-isogeny of a projective Montgomery point (X2:Z2) of order 2.
  // Input:  projective point of order two P = (X2:Z2).
  // Output: the 2-isogenous Montgomery curve with projective coefficients A/C.
```
The specification of the output is not correct. The parameters `A` and `C` should be renamed to `A24plus` and `C24` and the output spec should read 
```
  // Output: the 2-isogoneous Montgomery curve with projective coefficients A'/C' where A'+2C' = A24plus and 4C' = C24.
``` 
A similar phrasing should be used for the output spec of `get_4_isog`.
This would align with the specification document available on [sike.org](https://sike.org/).

**Comment by patricklonga** [comment]
Thanks for pointing this out. Comments are fixed now.
