### ISSUE TITLE
Unused pre-loop init

### ISSUE THREAD

**Issue by christianpaquin** [microsoft/PQCrypto-SIDH#55]
Looks like [line 662 from ec_isogeny.c](https://github.com/microsoft/PQCrypto-SIDH/blob/master/src/ec_isogeny.c#L662) isn't used; it is re-initialized on line 671 and therefore should be removed.

This was noted by the scan-build tool on the OQS project; see [PR  1211](https://github.com/open-quantum-safe/liboqs/pull/1211).

**Comment by patricklonga** [comment]
Good catch. Thanks, Christian. It's fixed now.
