### ISSUE TITLE
Use Curve255719 for this Encryption

### ISSUE THREAD

**Issue by YT-Advanced** [microsoft/PQCrypto-SIDH#56]
Hello, look like this Encryptions Algorithm use NIST curve. As I known, in 2013, Bernstein was discovered that the NSA had potentially implemented a backdoor into the P-256 curve based [Dual_EC_DRBG](https://en.wikipedia.org/wiki/Dual_EC_DRBG) algorithm. So I think Curve255719 is better to use on SIDH

**Comment by patricklonga** [comment]
Nope, it doesn't.
