### ISSUE TITLE
Non-Interactive Digital Signatures

### ISSUE THREAD

**Issue by OverclockedSanic** [Microsoft/PQCrypto-SIDH#9]
In some cases it can be really annoying having to use 2 different algorithms for Encryption and Signatures. For example, I have to use [GLYPH](https://github.com/quantumsafelattices/glyph) for signatures (which has 2KB public key sizes, which is okay compared to other PQC algorithms, but can still be inconvenient compared to traditional ECC or even SIDH/SIKE) and SIKE for encryption. Implementing both a good encryption scheme and a signature scheme that can use the same algorithm can be very useful, especially in decentralized systems like [Tox](https://tox.chat/) and [Bitcoin](https://bitcoin.org/en/). [This whitepaper](https://uwspace.uwaterloo.ca/bitstream/handle/10012/12408/Yoo_Youngho.pdf?sequence=1&isAllowed=y) discusses a possible implementation.

**Comment by patricklonga** [comment]
Unfortunately, isogeny-based signatures are still far from practical. So, for the moment, the SIDH library will only support KEX and KEM schemes.

**Comment by Hans-MartinHannibalLauridsen** [comment]
Bummer having something like:
Y. Yoo et al. “A post-quantum digital signature scheme based on supersingular isogenies”.
In: International Conference on Financial Cryptography and Data Security.
Springer. 2017, pp. 163–181.
directly in this library, uptodate and supported on windows/MS Visual Studio would be cool.
